# Generated by Django 3.2.25 on 2025-01-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_rejected',
        ),
    ]
