# Generated by Django 3.2.25 on 2025-01-04 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_auto_20250103_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='updated',
            new_name='updated_user',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created',
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='added_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_added_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
