# Generated by Django 3.2.25 on 2025-01-22 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0004_auto_20250111_1333'),
        ('cart', '0002_auto_20250115_1601'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('type', models.CharField(max_length=500)),
                ('sort', models.IntegerField(blank=True, default=0, null=True)),
                ('user_type', models.IntegerField()),
            ],
            options={
                'db_table': 'CancellationChoices',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('discounted_price', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('expected_time_minutes', models.IntegerField(default=0)),
                ('addr1', models.TextField(blank=True, null=True)),
                ('addr2', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('landmark', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('phoneno', models.TextField(blank=True, null=True)),
                ('pincode', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('PaymentDone', 'PaymentDone'), ('PaymentPending', 'PaymentPending'), ('PaymentFailed', 'PaymentFailed'), ('Placed', 'Placed'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Modified', 'Modified'), ('Delivered', 'Delivered'), ('CancelledCustomer', 'CancelledCustomer'), ('CancelledMerchant', 'CancelledMerchant'), ('Undelivered', 'Undelivered')])),
                ('order_id', models.TextField(unique=True)),
                ('discount_code', models.TextField(blank=True, null=True)),
                ('total_weight', models.FloatField()),
                ('delivery_price', models.FloatField(blank=True, null=True)),
                ('prod_discount', models.FloatField(blank=True, default=0, null=True)),
                ('del_discount', models.FloatField(blank=True, default=0, null=True)),
                ('has_been_refunded', models.BooleanField(default=False)),
                ('estimated_distance', models.FloatField(blank=True, null=True)),
                ('delivery_order_id', models.TextField(blank=True, null=True)),
                ('modification_count', models.IntegerField(default=0)),
                ('to_name', models.TextField(blank=True, null=True)),
                ('locality', models.TextField(blank=True, null=True)),
                ('to_house_number', models.TextField(blank=True, null=True)),
                ('cancellation_comment', models.TextField(blank=True, max_length=500, null=True)),
                ('cancellation_choices', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.cancellationchoices')),
                ('cancelled', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_cancelled_user', to=settings.AUTH_USER_MODEL)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cartitems', to='cart.cart')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_created_user', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_shop', to='shop.shop')),
            ],
        ),
    ]
