# Generated by Django 3.2.25 on 2025-01-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderidcounter',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'OrderIdCounter',
            },
        ),
    ]
