# Generated by Django 3.2.25 on 2025-01-23 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderidcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderupdates',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modification', models.TextField(blank=True, null=True)),
                ('modified_by', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='orderupdates', to='order.order', to_field='order_id')),
            ],
        ),
    ]
