# Generated by Django 3.2.25 on 2025-01-11 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_auto_20250111_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='created',
            new_name='created_user',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='updated',
            new_name='updated_user',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='updated',
            new_name='updated_user',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='created',
        ),
        migrations.AddField(
            model_name='shop',
            name='created_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_created_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
