# Generated by Django 3.2.25 on 2025-01-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20250111_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='shop',
        ),
        migrations.AddField(
            model_name='shop',
            name='address_shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='shop.address'),
        ),
    ]
