# Generated by Django 3.2.25 on 2025-01-15 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('shop', '0004_auto_20250111_1333'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'new'), ('transaction initiated', 'transaction initiated'), ('checked out', 'checked out'), ('removed', 'removed')], default='new', max_length=30)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('weight_id', models.IntegerField(blank=True, null=True)),
                ('delivery_amt', models.FloatField(blank=True, null=True)),
                ('est_distance', models.FloatField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_shop', to='shop.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Cartitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem_cart', to='cart.cart')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem_inventry', to='shop.inventory')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem_variant', to='product.productvariant')),
            ],
            options={
                'db_table': 'CartItem',
            },
        ),
    ]
