# Generated by Django 3.2.25 on 2025-01-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
